"""add_confirmations

Revision ID: 35d5ebc86494
Revises: a51db7ccfba1
Create Date: 2026-02-14 14:04:34.900389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d5ebc86494'
down_revision: Union[str, Sequence[str], None] = 'a51db7ccfba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crossdocking_confirmations',
    sa.Column('confirmation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('confirmation_number', sa.String(length=100), nullable=False),
    sa.Column('delivery_date', sa.String(length=20), nullable=True),
    sa.Column('deliver_to_code', sa.String(length=50), nullable=True),
    sa.Column('deliver_to_name', sa.String(length=200), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('confirmation_id')
    )
    op.create_index('idx_confirmation_company_id', 'crossdocking_confirmations', ['company_id'], unique=False)
    op.create_index('idx_confirmation_company_number', 'crossdocking_confirmations', ['company_id', 'confirmation_number'], unique=True)
    op.add_column('crossdocking_orders', sa.Column('confirmation_id', sa.BigInteger(), nullable=True))
    op.add_column('crossdocking_orders', sa.Column('confirmation_number', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'crossdocking_orders', 'crossdocking_confirmations', ['confirmation_id'], ['confirmation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crossdocking_orders', type_='foreignkey')
    op.drop_column('crossdocking_orders', 'confirmation_number')
    op.drop_column('crossdocking_orders', 'confirmation_id')
    op.drop_index('idx_confirmation_company_number', table_name='crossdocking_confirmations')
    op.drop_index('idx_confirmation_company_id', table_name='crossdocking_confirmations')
    op.drop_table('crossdocking_confirmations')
    # ### end Alembic commands ###
