"""auto_20260207_182324

Revision ID: 49d382b10383
Revises: 75480f6e2482
Create Date: 2026-02-07 18:23:30.091111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d382b10383'
down_revision: Union[str, Sequence[str], None] = '75480f6e2482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crossdocking_orders', sa.Column('pdf_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crossdocking_orders', 'pdf_url')
    # ### end Alembic commands ###
