"""auto_20260206_194655

Revision ID: 75480f6e2482
Revises: 
Create Date: 2026-02-06 19:47:00.011133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75480f6e2482'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crossdocking_orders',
    sa.Column('order_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('creation_date', sa.String(length=20), nullable=True),
    sa.Column('delivery_date', sa.String(length=20), nullable=True),
    sa.Column('deliver_to', sa.String(length=200), nullable=True),
    sa.Column('discounts', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('taxes', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('total_quantities', sa.BigInteger(), nullable=True),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('client_gln', sa.String(length=50), nullable=True),
    sa.Column('line_count', sa.BigInteger(), nullable=True),
    sa.Column('dispatch_gln', sa.String(length=50), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('supplier_gln', sa.String(length=50), nullable=True),
    sa.Column('supplier_internal_code', sa.String(length=50), nullable=True),
    sa.Column('bgm011', sa.String(length=50), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('event', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index('idx_order_company_document', 'crossdocking_orders', ['company_id', 'document_number'], unique=True)
    op.create_index('idx_order_company_id', 'crossdocking_orders', ['company_id'], unique=False)
    op.create_index('idx_order_document_number', 'crossdocking_orders', ['document_number'], unique=False)
    op.create_table('crossdocking_order_lines',
    sa.Column('line_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('line_number', sa.BigInteger(), nullable=False),
    sa.Column('internal_code', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('client_article_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('units_per_box', sa.BigInteger(), nullable=True),
    sa.Column('quantity_ordered', sa.BigInteger(), nullable=True),
    sa.Column('units_ordered', sa.BigInteger(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('discount', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('tax', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('quantity_dispatched', sa.BigInteger(), nullable=True),
    sa.Column('dispatch_rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('quantity_received', sa.BigInteger(), nullable=True),
    sa.Column('article_code', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['crossdocking_orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_id')
    )
    op.create_index('idx_order_line_order_id', 'crossdocking_order_lines', ['order_id'], unique=False)
    op.create_table('crossdocking_sale_points',
    sa.Column('sale_point_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('store_number', sa.String(length=20), nullable=True),
    sa.Column('store_name', sa.String(length=200), nullable=True),
    sa.Column('full_name', sa.String(length=250), nullable=True),
    sa.Column('total_boxes', sa.BigInteger(), nullable=True),
    sa.Column('total_units', sa.BigInteger(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['crossdocking_orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sale_point_id')
    )
    op.create_index('idx_crossdocking_sp_order_id', 'crossdocking_sale_points', ['order_id'], unique=False)
    op.create_table('crossdocking_items',
    sa.Column('item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sale_point_id', sa.BigInteger(), nullable=False),
    sa.Column('internal_code', sa.String(length=50), nullable=True),
    sa.Column('original_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.BigInteger(), nullable=True),
    sa.Column('units_per_box', sa.BigInteger(), nullable=True),
    sa.Column('total_units', sa.BigInteger(), nullable=True),
    sa.Column('sent', sa.BigInteger(), nullable=True),
    sa.Column('missing', sa.BigInteger(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sale_point_id'], ['crossdocking_sale_points.sale_point_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('idx_crossdocking_item_sp_id', 'crossdocking_items', ['sale_point_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_crossdocking_item_sp_id', table_name='crossdocking_items')
    op.drop_table('crossdocking_items')
    op.drop_index('idx_crossdocking_sp_order_id', table_name='crossdocking_sale_points')
    op.drop_table('crossdocking_sale_points')
    op.drop_index('idx_order_line_order_id', table_name='crossdocking_order_lines')
    op.drop_table('crossdocking_order_lines')
    op.drop_index('idx_order_document_number', table_name='crossdocking_orders')
    op.drop_index('idx_order_company_id', table_name='crossdocking_orders')
    op.drop_index('idx_order_company_document', table_name='crossdocking_orders')
    op.drop_table('crossdocking_orders')
    # ### end Alembic commands ###
