"""add_normalized_tables

Revision ID: 7deff17aef26
Revises: 8fb71e37c9a0
Create Date: 2026-02-16 14:02:08.864216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7deff17aef26'
down_revision: Union[str, Sequence[str], None] = '8fb71e37c9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('client_gln', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index('idx_client_company_gln', 'clients', ['company_id', 'client_gln'], unique=True)
    op.create_index('idx_client_company_id', 'clients', ['company_id'], unique=False)
    op.create_table('departments',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('department_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('supplier_code', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_index('idx_department_client_code', 'departments', ['client_id', 'department_code'], unique=True)
    op.create_index('idx_department_client_id', 'departments', ['client_id'], unique=False)
    op.create_index('idx_department_company_id', 'departments', ['company_id'], unique=False)
    op.create_table('stores',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('store_code', sa.String(length=20), nullable=False),
    sa.Column('store_name', sa.String(length=200), nullable=True),
    sa.Column('slot_id', sa.String(length=20), nullable=True),
    sa.Column('chain', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index('idx_store_client_id', 'stores', ['client_id'], unique=False)
    op.create_index('idx_store_company_client_code', 'stores', ['company_id', 'client_id', 'store_code'], unique=True)
    op.create_index('idx_store_company_id', 'stores', ['company_id'], unique=False)
    op.add_column('crossdocking_confirmations', sa.Column('deliver_to_store_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'crossdocking_confirmations', 'stores', ['deliver_to_store_id'], ['store_id'])
    op.add_column('crossdocking_items', sa.Column('product_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'crossdocking_items', 'products', ['product_id'], ['id'])
    op.add_column('crossdocking_order_lines', sa.Column('product_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'crossdocking_order_lines', 'products', ['product_id'], ['id'])
    op.add_column('crossdocking_orders', sa.Column('client_id', sa.UUID(), nullable=True))
    op.add_column('crossdocking_orders', sa.Column('deliver_to_store_id', sa.UUID(), nullable=True))
    op.add_column('crossdocking_orders', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'crossdocking_orders', 'departments', ['department_id'], ['department_id'])
    # NOT VALID: existing orders may reference company_ids not yet in organizations.
    # Will be validated after reparsing populates the organizations table.
    op.execute(
        'ALTER TABLE crossdocking_orders '
        'ADD CONSTRAINT fk_orders_organization '
        'FOREIGN KEY (company_id) REFERENCES organizations (id) NOT VALID'
    )
    op.create_foreign_key(None, 'crossdocking_orders', 'clients', ['client_id'], ['client_id'])
    op.create_foreign_key(None, 'crossdocking_orders', 'stores', ['deliver_to_store_id'], ['store_id'])
    op.add_column('crossdocking_sale_points', sa.Column('store_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'crossdocking_sale_points', 'stores', ['store_id'], ['store_id'])
    op.add_column('organizations', sa.Column('gln', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('internal_code', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # NOTE: Not dropping existing BeautyMarket columns from organizations — shared table
    op.add_column('products', sa.Column('internal_code', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('original_code', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('client_article_code', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('units_per_box', sa.BigInteger(), nullable=True))
    op.create_index('idx_product_org_internal_code', 'products', ['organization_id', 'internal_code'], unique=True)
    # NOTE: Not dropping existing BeautyMarket columns/constraints from products — shared table
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_product_org_internal_code', table_name='products')
    op.drop_column('products', 'units_per_box')
    op.drop_column('products', 'code')
    op.drop_column('products', 'client_article_code')
    op.drop_column('products', 'original_code')
    op.drop_column('products', 'internal_code')
    op.drop_column('organizations', 'logo_url')
    op.drop_column('organizations', 'internal_code')
    op.drop_column('organizations', 'gln')
    op.drop_constraint(None, 'crossdocking_sale_points', type_='foreignkey')
    op.drop_column('crossdocking_sale_points', 'store_id')
    op.drop_constraint('fk_orders_organization', 'crossdocking_orders', type_='foreignkey')
    op.drop_constraint(None, 'crossdocking_orders', type_='foreignkey')
    op.drop_constraint(None, 'crossdocking_orders', type_='foreignkey')
    op.drop_constraint(None, 'crossdocking_orders', type_='foreignkey')
    op.drop_column('crossdocking_orders', 'department_id')
    op.drop_column('crossdocking_orders', 'deliver_to_store_id')
    op.drop_column('crossdocking_orders', 'client_id')
    op.drop_constraint(None, 'crossdocking_order_lines', type_='foreignkey')
    op.drop_column('crossdocking_order_lines', 'product_id')
    op.drop_constraint(None, 'crossdocking_items', type_='foreignkey')
    op.drop_column('crossdocking_items', 'product_id')
    op.drop_constraint(None, 'crossdocking_confirmations', type_='foreignkey')
    op.drop_column('crossdocking_confirmations', 'deliver_to_store_id')
    op.drop_index('idx_store_company_id', table_name='stores')
    op.drop_index('idx_store_company_client_code', table_name='stores')
    op.drop_index('idx_store_client_id', table_name='stores')
    op.drop_table('stores')
    op.drop_index('idx_department_company_id', table_name='departments')
    op.drop_index('idx_department_client_id', table_name='departments')
    op.drop_index('idx_department_client_code', table_name='departments')
    op.drop_table('departments')
    op.drop_index('idx_client_company_id', table_name='clients')
    op.drop_index('idx_client_company_gln', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
