"""auto_20260211_111351

Revision ID: 8d3e1307cd3a
Revises: b2c3d4e5f6g7
Create Date: 2026-02-11 11:13:57.138991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3e1307cd3a'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crossdocking_orders', sa.Column('deliver_to_code', sa.String(length=50), nullable=True))
    op.add_column('crossdocking_orders', sa.Column('deliver_to_name', sa.String(length=200), nullable=True))
    op.drop_column('crossdocking_orders', 'deliver_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crossdocking_orders', sa.Column('deliver_to', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('crossdocking_orders', 'deliver_to_name')
    op.drop_column('crossdocking_orders', 'deliver_to_code')
    # ### end Alembic commands ###
