"""add_confirmation_status

Revision ID: 8fb71e37c9a0
Revises: 35d5ebc86494
Create Date: 2026-02-15 07:28:19.157624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb71e37c9a0'
down_revision: Union[str, Sequence[str], None] = '35d5ebc86494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crossdocking_confirmations', sa.Column('confirmation_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crossdocking_confirmations', 'confirmation_status')
    # ### end Alembic commands ###
