"""auto_20260211_113051

Revision ID: cada3b2c7d18
Revises: 8d3e1307cd3a
Create Date: 2026-02-11 11:30:56.236758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cada3b2c7d18'
down_revision: Union[str, Sequence[str], None] = '8d3e1307cd3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crossdocking_orders', sa.Column('subtotal', sa.Numeric(precision=18, scale=5), nullable=True))
    op.add_column('crossdocking_orders', sa.Column('net_total', sa.Numeric(precision=18, scale=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crossdocking_orders', 'net_total')
    op.drop_column('crossdocking_orders', 'subtotal')
    # ### end Alembic commands ###
