"""drop_denormalized_columns

Revision ID: fb21eb6dec2c
Revises: 77de496e1903
Create Date: 2026-02-16 23:43:19.140712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb21eb6dec2c'
down_revision: Union[str, Sequence[str], None] = '77de496e1903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crossdocking_confirmations', 'deliver_to_code')
    op.drop_column('crossdocking_confirmations', 'deliver_to_name')
    op.drop_column('crossdocking_items', 'original_code')
    op.drop_column('crossdocking_items', 'units_per_box')
    op.drop_column('crossdocking_items', 'description')
    op.drop_column('crossdocking_items', 'internal_code')
    op.drop_column('crossdocking_order_lines', 'description')
    op.drop_column('crossdocking_order_lines', 'internal_code')
    op.drop_column('crossdocking_order_lines', 'client_article_code')
    op.drop_column('crossdocking_order_lines', 'units_per_box')
    op.drop_column('crossdocking_order_lines', 'code')
    op.drop_column('crossdocking_orders', 'client_name')
    op.drop_column('crossdocking_orders', 'client_gln')
    op.drop_column('crossdocking_orders', 'supplier_internal_code')
    op.drop_column('crossdocking_orders', 'deliver_to_code')
    op.drop_column('crossdocking_orders', 'supplier_gln')
    op.drop_column('crossdocking_orders', 'supplier_name')
    op.drop_column('crossdocking_orders', 'deliver_to_name')
    op.drop_column('crossdocking_orders', 'dispatch_gln')
    op.drop_column('crossdocking_orders', 'department')
    op.drop_column('crossdocking_sale_points', 'store_name')
    op.drop_column('crossdocking_sale_points', 'store_number')
    op.drop_column('crossdocking_sale_points', 'slot_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crossdocking_sale_points', sa.Column('slot_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('crossdocking_sale_points', sa.Column('store_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('crossdocking_sale_points', sa.Column('store_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('crossdocking_orders', sa.Column('department', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('crossdocking_orders', sa.Column('dispatch_gln', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('crossdocking_orders', sa.Column('deliver_to_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('crossdocking_orders', sa.Column('supplier_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('crossdocking_orders', sa.Column('supplier_gln', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('crossdocking_orders', sa.Column('deliver_to_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('crossdocking_orders', sa.Column('supplier_internal_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('crossdocking_orders', sa.Column('client_gln', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('crossdocking_orders', sa.Column('client_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('crossdocking_order_lines', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('crossdocking_order_lines', sa.Column('units_per_box', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('crossdocking_order_lines', sa.Column('client_article_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('crossdocking_order_lines', sa.Column('internal_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('crossdocking_order_lines', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('crossdocking_items', sa.Column('internal_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('crossdocking_items', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('crossdocking_items', sa.Column('units_per_box', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('crossdocking_items', sa.Column('original_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('crossdocking_confirmations', sa.Column('deliver_to_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('crossdocking_confirmations', sa.Column('deliver_to_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
